#!/usr/bin/env python3
import re
import os

if __name__ == '__main__':
    WEBRipPATH = "/home/peter/mnt/samba/half-life/media/video/WEBRip/"

    videoIDInfo = {}
    for root, dirs, files in os.walk(WEBRipPATH):
        for file in files:
            filePath = os.path.join(root, file)
            rule = re.compile(r"(.+)\s+\[(.+)\]\.(mkv|mp4|webm)")

            matchRes = rule.search(file)
            if not matchRes:
                continue
            vid = matchRes.group(2)
            try:
                videoIDInfo[vid].append(filePath)
            except KeyError as e:
                videoIDInfo[vid] = [filePath]

        for directory in dirs:
            pass

    for k, v in videoIDInfo.items():
        dupCnt = len(v)
        if dupCnt == 1:
            continue
        print("[%s] duplication found(count %3d)" % (k, dupCnt))
        for idx, p in enumerate(v):
            print("%4d:%s" % (idx, p))
        print()
