#!/usr/bin/env python3
import os
import shlex

if __name__ == '__main__':
    fstabLines = []
    with open("/etc/fstab", 'r') as fstabFile:
        lines = fstabFile.readlines()
        fstabLines = [l[:-1] for l in lines]
    for idx,rule in enumerate(fstabLines):
        if len(rule) == 0:
            continue
        if rule[0] == '#':
            continue
        split = shlex.split(rule)
        if len(split) != 6:
            continue
        fstabLines[idx] = split

    fieldMaxLen=[0 for i in range(0,4)]
    for fieldIdx in range(0,4):
        for idx,rule in enumerate(fstabLines):
            if type(rule) is not list:
                continue
            thisSize=len(rule[fieldIdx])
            if fieldMaxLen[fieldIdx]<thisSize:
                fieldMaxLen[fieldIdx]=thisSize

    print(fieldMaxLen)

    for ruleIdx,rule in enumerate(fstabLines):
        if type(rule) is not list:
            continue
        for fieldIdx,field in enumerate(fstabLines[ruleIdx]):
            if fieldIdx>=4:
                break
            while len(fstabLines[ruleIdx][fieldIdx])<fieldMaxLen[fieldIdx]:
                fstabLines[ruleIdx][fieldIdx]+=' '

    for ruleIdx,rule in enumerate(fstabLines):
        if type(rule) is not list:
            continue
        fstabLines[ruleIdx]=' '.join(fstabLines[ruleIdx])

    for rule in fstabLines:
        print(rule)

    with open("/etc/fstab", 'w') as fstabFile:
        for rule in fstabLines:
            fstabFile.write(rule)
            fstabFile.write(os.linesep)
    
